# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
          - v2
    docker:
      - image: circleci/node:6.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:circleci
      # run build!
      - run: npm run build
#      # run sync!
#      - run: npm run db:sync
#      # TODO: add migration step here..
#      # run sync!
#      - run: npm run sls:deploy


